API_HOST_URL: 'https://dev.mexicox.gob.mx'
SSO_URL: 'https://dev.mexicox.gob.mx'
SSO_FINISHED_URL: 'https://dev.mexicox.gob.mx'
ENVIRONMENT_DISPLAY_NAME: 'Cursos'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
OAUTH_CLIENT_ID: 'zrxzez1eCwVzjNNHzuerPmt5uso7guriA2TpqDiN'

PLATFORM_NAME: "OpenEdX"
PLATFORM_FULL_NAME: "OpenEdX"
TOKEN_TYPE: "JWT"

AGREEMENT_URLS:
  PRIVACY_POLICY_URL: ''
  COOKIE_POLICY_URL: ''
  DATA_SELL_CONSENT_URL: ''
  TOS_URL: ''
  EULA_URL: ''
  SUPPORTED_LANGUAGES: []

DISCOVERY:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    COURSE_DETAIL_TEMPLATE: ''
    PROGRAM_DETAIL_TEMPLATE: ''

PROGRAM:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    PROGRAM_DETAIL_TEMPLATE: ''

DASHBOARD:
  TYPE: 'gallery'

SSO_BUTTON_TITLE:
  ar: "الدخول عبر SSO"
  en: "Sign in with SSO"

FIREBASE:
  ENABLED: false
  CLOUD_MESSAGING_ENABLED: false
  PROJECT_NUMBER: ''
  PROJECT_ID: ''
  APPLICATION_ID: ''
  API_KEY: ''

BRAZE:
  ENABLED: false
  PUSH_NOTIFICATIONS_ENABLED: false

GOOGLE:
  ENABLED: true
  CLIENT_ID: '12345678909876523'

MICROSOFT:
  ENABLED: false
  CLIENT_ID: ''

FACEBOOK:
  ENABLED: false
  FACEBOOK_APP_ID: ''
  CLIENT_TOKEN: ''

BRANCH:
  ENABLED: false
  KEY: ''
  URI_SCHEME: ''
  HOST: ''
  ALTERNATE_HOST: ''

WHATS_NEW_ENABLED: false
SOCIAL_AUTH_ENABLED: true
REGISTRATION_ENABLED: true
BROWSER_LOGIN: false
BROWSER_REGISTRATION: false
PRE_LOGIN_EXPERIENCE_ENABLED: true

EXPERIMENTAL_FEATURES:
  APP_LEVEL_DOWNLOADS:
    ENABLED: false

UI_COMPONENTS:
  COURSE_UNIT_PROGRESS_ENABLED: false
  COURSE_NESTED_LIST_ENABLED: false
  COURSE_DROPDOWN_NAVIGATION_ENABLED: false
  COURSE_DOWNLOAD_QUEUE_SCREEN: false
  LOGIN_REGISTRATION_ENABLED: true
  SAML_SSO_LOGIN_ENABLED: false
  SAML_SSO_DEFAULT_LOGIN_BUTTON: false

LLAVEMX:
  ENABLED: true
  CLIENT_ID: "202602091646467055"
  REDIRECT_URI: "mx.aprende.ios://oauth/callback"
